using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace adapter.Model.apicaldata
{
    public static class DepartmentMapper
    {
        public static string? GetDepartmentCode(string departmentName)
        {
            return departmentName.Trim() switch
            {
                "Sociology & Philosophy" => "SOC & PHI",
                "History & Philosophy" => "HIS & PHI",
                "Political Science & Philosophy" => "PLS + PHI",
                "English & Philosophy" => "ENG + PHI",
                "National Service Scheme" => "NSS",
                "English & Education" => "ENED",
                "English & Political Science" => "ENPS",
                "English & Psychology" => "ENPY",
                "English & History" => "ENHI",
                "Sociology & English" => "SOEN",
                "Psychology & English" => "PYEN",
                "English & Geography" => "ENGE",
                "Sociology & Education" => "SOED",
                "English & Mass Communication & Journalism" => "ENMC",
                "English & Music" => "ENMU",
                "English & Physical Education" => "ENPE",
                "Psychology & Music" => "PYMU",
                "Psychology & Physical Education" => "PYPE",
                "English & Sociology" => "ENSO",
                "Psychology & Sociology" => "PYSO",
                "English & Social Work" => "ENSW",
                "Psychology & Social Work" => "PYSW",
                "Education & English" => "EDEN",
                "History & English" => "HIEN",
                "Education & Psychology" => "EDPS",
                "History & Geography" => "HIGE",
                "Education & Physical Education" => "EDPE",
                "Education & Sociology" => "EDSO",
                "History & Tourism" => "HITO",
                "Education & Social Work" => "EDSW",
                "Geography & English" => "GEEN",
                "Political Science & English" => "PSEN",
                "Geography & Political Science" => "GEPS",
                "Political Science & History" => "PSHI",
                "Geography & History" => "GEHI",
                "Political Science & Geography" => "PSGE",
                "Mass Communication & English" => "MCEN",
                "Political Science & Psychology" => "PSPY",
                "Political Science & Social Work" => "PSSW",
                "Mass Communication & Political Science" => "MCPS",
                "Mass Communication & Psychology" => "MCPY",
                "Music & English" => "MUEN",
                "Music & Psychology" => "MUPY",
                "Music & Mass Communication & Journalism" => "MUMC",
                "Physical Education & English" => "PEEN",
                "Physical Education & Education" => "PEED",
                "Physical Education & Psychology" => "PEPY",
                "Physical Education & Music" => "PEMU",
                "Sociology & Psychology" => "SOPY",
                "Sociology & Geography" => "SOGE",
                "Sociology & Social Work" => "SOSW",
                "Social Work & English" => "SWEN",
                "Social Work & Education" => "SWED",
                "Social Work & Psychology" => "SWPY",
                "Social Work & Mass Communication" => "SWMC",
                "Social Work & Political Science" => "SWPS",
                "Computer Science & Mathematics" => "CSMT",
                "Computer Science & Physics" => "CSPH",
                "Computer Science & Economics" => "CSEO",
                "Mathematics & Physics" => "MTPH",
                "Mathematics & Economics" => "MTEO",
                "Mathematics & Computer Science" => "MTCS",
                "Physics & Computer Science" => "PHCS",
                "Physics & Mathematics" => "PHMT",
                "Economics & Computer Science" => "EOCS",
                "Economics & Mathematics" => "EOMT",
                "Political Science & Mass Communication" => "PSMC",
                "Psychology & Mass Communication" => "PYMC",
                "Sociology & Political Science" => "SOPS",
                "Psychology & Education" => "PYED",
                "Social Work & Sociology" => "SWSO",
                "History & Education" => "HIED",
                "History & Political Science" => "HIPO",
                "Geography & Sociology" => "GESO",
                "Mass Communication & Education" => "MCED",
                "Mass Communication & Physical Education" => "MCPE",
                "Mass Communication & Sociology" => "MCSO",
                "Physical Education & Mass Communication" => "PEMC",
                "Economics & Statistics" => "ECST",
                "Education & Political Science" => "EDPO",
                "Mass Communication & Social Work" => "MCSW",
                "Physical Education & Political Science" => "PEPO",
                "Psychology & Political Science" => "PYPO",
                "History & Mass Communication" => "HIMC",
                "Political Science & Sociology" => "PSSO",
                "Sociology & Mass Communication" => "SOMC",
                "Sociology & History" => "SOHI",
                "History & Sociology" => "HISO",
                "Data Science & Mathematics" => "DSMT",
                "Political Science & Music" => "PSMU",
                "Geography & Music" => "GEMU",
                "Mass Communication & Music" => "MCMU",
                "Economics & Political Science" => "EOPS",
                "Education & Mass Communication" => "EDMC",
                "Data Science" => "BCA",
                "Artificial Intelligence & Machine Learning"=>"BCA",
                "Banking & Finance" => "BCOM",
                "Accounting & Taxation" => "BCOM",
                "Counselling Psychology" => "MSCPSY - I",
                "Organisational Psychology" => "MSCPSY - I",
                _ => null
            };
        }
    }
}