using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace adapter.Model.classmodel
{
    public class AdmReceiveApplication
    {
        public string SETTLEMENT_DATE { get; set; }
        public string STATUS_ID { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string FATHER_AGE { get; set; }
        public string MOTHER_AGE { get; set; }
        public string IS_NRI { get; set; }
        public string AADHAR_NUMBER { get; set; }
        public string RECEIVE_ID { get; set; }
        public string ISSUE_ID { get; set; }
        public string UNIQUE_ID { get; set; }
        public string PROGRAMME_LEVEL { get; set; }
        public string BRANCH_OF_STUDY { get; set; }
        public string MOTHER_NAME { get; set; }
        public string SMS_MOBILE_NO { get; set; }
        public string LAST_STUDIED_STATE { get; set; }
        public string LAST_STUDIED_INSTITUTION { get; set; }
        public string TRANSACTION_MODE { get; set; }
        public string TRANSACTION_ID { get; set; }
        public string DDNUMBER { get; set; }
        public string BRANCH { get; set; }
        public string DDOR_TRANSACTION_DATE { get; set; }
        public string DDTAKEN_PLACE { get; set; }
        public string DDTAKEN_BANK { get; set; }
        public string APPLICATION_TYPE_ID { get; set; }
        public string APPLICATION_NO { get; set; }
        public string MODE_ID { get; set; }
        public string PROGRAMME_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string AGE { get; set; }
        public string GENDER { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string COMMUNITY_ID { get; set; }
        public string CASTE_ID { get; set; }
        public string NATIONALITY_ID { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public string RELIGION_ID { get; set; }
        public string MOTHER_TONGUE { get; set; }
        public string FATHER_NAME { get; set; }
        public string OCCUPATION { get; set; }
        public string ANNUAL_INCOME { get; set; }
        public string ECONOMIC_STATUS_ID { get; set; }
        public string MARITAL_STATUS_ID { get; set; }
        public string PARISHI_FRC { get; set; }
        public string IS_FIRSTGENERATION { get; set; }
        public string IS_GOVERNMENT { get; set; }
        public string ENTRANCE_REGISTER_NO { get; set; }
        public string ENTRANCE_MARK { get; set; }
        public string SPECIALLYABLED_ID { get; set; }
        public string EXSERVICE_MAN { get; set; }
        public string TAMIL_ORGIN { get; set; }
        public string LIVING_MODE_ID { get; set; }
        public string SPORTS { get; set; }
        public string LEVEL { get; set; }
        public string EXTRA_CURRICULAR { get; set; }
        public string EXAM_PASSED { get; set; }
        public string YEAR_OF_PASSING { get; set; }
        public string MEDIUM { get; set; }
        public string SCHOOL_OR_COLLEGE { get; set; }
        public string LAST_STUDIED_PLACE { get; set; }
        public string MAIN_SUBJECT_PG { get; set; }
        public string HSC_GROUP { get; set; }
        public string NO_OF_ATTEMPT { get; set; }
        public string REMARK { get; set; }
        public string RECEIVE_DATE { get; set; }
        public string EDUCATION_BOARD_ID { get; set; }
        public string VOCATIONAL_GROUP { get; set; }
        public string CDOORDETAIL { get; set; }
        public string CSTREET { get; set; }
        public string CVILLAGE_AREA { get; set; }
        public string CPOST_PLACE_TOWN { get; set; }
        public string CTALUK_CITY { get; set; }
        public string CDISTRICT { get; set; }
        public string CSTATE { get; set; }
        public string CPINCODE { get; set; }
        public string CCOUNTRY { get; set; }
        public string CPHONENO { get; set; }
        public string CMOBILENO { get; set; }
        public string PDOORDETAIL { get; set; }
        public string PSTREET { get; set; }
        public string PVILLAGE_AREA { get; set; }
        public string PPOST_PLACE_TOWN { get; set; }
        public string PTALUK_CITY { get; set; }
        public string PDISTRICT { get; set; }
        public string PSTATE { get; set; }
        public string PPINCODE { get; set; }
        public string PCOUNTRY { get; set; }
        public string PPHONENO { get; set; }
        public string PMOBILENO { get; set; }
        public string HSTOTAL { get; set; }
        public string STAFF_ID { get; set; }
        public string IS_DELETED { get; set; }
        public string AGGREGATE_PERCENTAGE { get; set; }
        public string HONOUR_SPERCENTAGE { get; set; }
        public string PROGGROUP_ID { get; set; }
        public string HSPERCENTAGE { get; set; }
        public string HONOUR_SUBJECT { get; set; }
        public string HOSTEL_FACILITY { get; set; }
        public string ONLINE_USER { get; set; }
        public string IS_ENTRANCE_BASED { get; set; }
        public string IS_SINGLE_GIRL_CHILD { get; set; }
        public string ONLINE_APPLICATION_COST { get; set; }
        public string IS_COURIERSENT { get; set; }
        public string NOTRANS_ATTEMPT { get; set; }
        public string ENTRANCE_ROLLNO { get; set; }
        public string CLUBMEMID { get; set; }
        public string UG_PROGRAMME_ID { get; set; }
        public string UG_TOTAL_MARK { get; set; }
        public string HS_MAX_MARK { get; set; }
        public string IS_SPOT_ADM { get; set; }
        public string MOTHER_MOBILE_NUMBER { get; set; }
        public string FATHER_MOBILE_NUMBER { get; set; }
        public string HAILING_FROM { get; set; }
        public string EMAIL_ID { get; set; }
        public string ISRC { get; set; }
        public string RCCATEGORY { get; set; }
        public string ROLL_NO { get; set; }
        public string BATCH_ID { get; set; }
        public string LAST_STUDIED_SCHOOL { get; set; }
        public string UG_LAST_COLLEGE_STUDIED { get; set; }
        public string UG_LAST_COLLEGE_PLACE { get; set; }
        public string LAST_STUDIED_CLASS { get; set; }
        public string TOTAL_CUT_OFF_MARK { get; set; }
        public string UG_YEAR_OF_PASSING { get; set; }
        public string BLOOD_GROUP { get; set; }
        public string DIOCESE_OR_CONGREGATION { get; set; }
        public string IS_DALIT { get; set; }
        public string STATUS { get; set; }
        public string UNIVERSITY { get; set; }
        public string MOTHER_OCCUPATION { get; set; }
        public string IS_ROMAN_CATHOLIC { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string IS_REGISTERED_TENANT { get; set; }
        public string PHOTO_PATH { get; set; }
        public string IS_SUBMITTED { get; set; }
        public string HSC_NO { get; set; }
        public string IS_VERIFIED { get; set; }
        public string ISSUED_ID { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string PROGRAMME_GROUP_ID { get; set; }
        public string IS_PAID { get; set; }
        public string PAYMENT_MODE { get; set; }
        public string RAZORPAY_ID { get; set; }
        public string SHIFT { get; set; }
        public string DOB { get; set; }
        public string SHIFT_NAME { get; set; }
        public string IS_FEE_PAID { get; set; }
        public string PROGRAMME_NAME { get; set; }
        public string STUDENT_ID { get; set; }
        public string PAYMENT_DATE { get; set; }
        public string STATUS_NAME { get; set; }
        public string CASTE { get; set; }
        public string RELIGION { get; set; }
        public string MAIN_COMMUNITY { get; set; }
        public string HOSTEL_NAME { get; set; }
        public string APPLICATION_TYPE { get; set; }
        public string CLASS_NAME { get; set; }
        public string CLASS { get; set; }
        public string PREFIX { get; set; }
        public string RUN_ID { get; set; }
        public string PROGRAMME_MODE { get; set; }
        public string DEPARTMENT { get; set; }
        public string CLASS_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string IS_AC_CREATED { get; set; }
        public string STU_EMAILID { get; set; }
        public string STU_MOBILENO { get; set; }
        public string BOID_IMAGE { get; set; }
        public string IS_ELEVENTH_PASS { get; set; }

        public string SINGLE_PARENT_PROOF { get; set; }
        public string PHYSICALY_CHALLENGED_PROOF { get; set; }
        public string EX_SERVICEMAN_PROOF { get; set; }
        public string COMMUNITY_PROOF { get; set; }
        public string NRI_PROOF { get; set; }
        public string IS_SINGLE_PARENT { get; set; }
        public string PHYSICALY_CHALLANGED_TYPE { get; set; }
        public string UG_TOTAL_SEMESTER { get; set; }
        public string GUARDIAN_NAME { get; set; }

        public string M_ANNUAL_INCOME { get; set; }
        public string M_OCCUPATION { get; set; }
        public string FR_MOBILE { get; set; }
        public string MR_MOBILE { get; set; }
        public string SPORTS_LEVEL { get; set; }
        public string IS_NCC_OR_NSS { get; set; }
        public string PHYSICALLY_CHALLENGED_PERCENTAGE { get; set; }
        public string FATHER_EDUCATION { get; set; }
        public string MOTHER_EDUCATION { get; set; }

        public string FEE_CATEGORY_ID { get; set; }
        public string HSS_GROUP_ID { get; set; }
        public string HSS_GROUP { get; set; }
        public string HSC_TOTAL { get; set; }
        public string HSC_MAX_MARK { get; set; }
        public string HSC_PERCENTAGE { get; set; }

        public string COMMUNITY { get; set; }
        public string MOBILE_NO { get; set; }
        public string PROGRAMME { get; set; }
        public string ROLE { get; set; }
        public string USER_TYPE { get; set; }
        public string ADMISSION_NO { get; set; }
        public string CLASS_YEAR { get; set; }
        public string PROGRAM_ID { get; set; }
        public string NATIONALITY { get; set; }
        public string CONTACT_NO { get; set; }
        public string IDENTIFICATION_MARK1 { get; set; }
        public string IDENTIFICATION_MARK2 { get; set; }
        public string PROGRAMME_DESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public string CERTIFICATE1 { get; set; }
        public string CERTIFICATE2 { get; set; }
        public string CERTIFICATE3 { get; set; }
        public string FR_OCCUPATION { get; set; }
        public string IS_PHYSICALLY_CHALLENGED { get; set; }
        public string HSS_SUBJECT { get; set; }
        public string MAX_MARK { get; set; }
        public string MARK { get; set; }
        public string M_PASS { get; set; }
        public string NO_OF_ATTEMPTS { get; set; }
        public string CAMPUS_ID { get; set; }
        public string APPLY_DATE { get; set; }
        
      
    }

    public class AdmissionRegisterEntry 
    {
        public string ADMISSION_NO { get; set; }
        public string PROGRAM_ID { get; set; }
        public string CLASS_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string GUARDIAN_NAME { get; set; }
        public string NATIONALITY { get; set; }
        public string RELIGION { get; set; }
        public string COMMUNITY { get; set; }
        public string CASTE { get; set; }
        public string GENDER { get; set; }
        public string CLASS_NAME { get; set; }
        public string CONTACT_NO { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string IDENTIFICATION_MARK1 { get; set; }
        public string IDENTIFICATION_MARK2 { get; set; }
        public string PROGRAMME_DESCRIPTION { get; set; }
        public string DEPARTMENT { get; set; }
        public string ADDRESS { get; set; }
        public string CLASS_YEAR { get; set; }
        public string CERTIFICATE1 { get; set; }
        public string CERTIFICATE2 { get; set; }
        public string CERTIFICATE3 { get; set; }
        public string MOTHER_TONGUE { get; set; }
        public string FR_OCCUPATION { get; set; }
        public string MOBILE_NO { get; set; }
        public string LAST_STUDIED_INSTITUTION { get; set; }
        public string LAST_STUDIED_PLACE { get; set; }
        public string HSC_NO { get; set; }
        public string ANNUAL_INCOME { get; set; }
        public string TC_SERIAL_NO { get; set; }
        public string FINE_NAME { get; set; }
        public string ADMITTED_CLASS { get; set; }
        public string ADMISSION_DATE { get; set; }
        public string TC_APPLIED_DATE { get; set; }
        public string TC_GIVEN_DATE { get; set; }
        public string CERTIFICATE_DATE { get; set; }
        public string HSC_TC_DATE { get; set; }
        public string COMMUNITY_NUMBER { get; set; }
        public string MEDIUM_OF_INSTRUCTION { get; set; }
        public string UNIVERSITY_ID { get; set; }
        public string UNIVERSITY { get; set; }
        public string APPLICATION_TYPE_ID { get; set; }
    }
}
